import pyautogui
from time import sleep
import time
import pyperclip
# The Wind and the Sun 한컴 타자 자동화
pyautogui.hotkey('win')
sleep(1)
pyperclip.copy('한컴 타자연습')
pyautogui.hotkey("ctrl", "v")
sleep(2)
pyautogui.press('enter')
sleep(5)
pyautogui.press('enter')
sleep(1)
pyautogui.click(1272, 289)
sleep(0.5)
pyautogui.click(762, 643)
sleep(1)
pyautogui.press('enter')
sleep(2)
pyautogui.click(905, 433)
sleep(1)
pyautogui.typewrite('The Wind and the Sun')
sleep(0.4)
pyautogui.press('space', presses=2, interval=0.3)
sleep(0.4)
pyautogui.typewrite('The North Wind was rushing along and blowing the clouds as he passed.')
sleep(0.4)
pyautogui.press('space', presses=2, interval=0.3)
sleep(0.4)
pyautogui.typewrite('"Who is so strong as I ?" he cried.')
sleep(0.4)
pyautogui.press('space', presses=2, interval=0.3)
sleep(0.4)
pyautogui.typewrite('"I am even stronger than the sun."')
sleep(0.4)
pyautogui.press('space', presses=2, interval=0.3)
sleep(0.4)
pyautogui.typewrite('"Can you show that you are stronger ?" asked the Sun.')
sleep(0.4)
pyautogui.press('space')
sleep(0.4)